services:
  pindar-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: pindar-fe
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
